name: Nodejs CI

on:
    push:
        branches:
            - main            
    pull_request:
        branches: 
            - main

jobs: 
   
  build: 
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [16.x, 18.x]  
      steps: 
          - name: checkout code 
            uses: actions/checkout@v3

          - name: checkout code 
            uses: actions/setup-node@v3
            with:
              node-version: '14'
          - name: Install dependencies
            run: npm install
        
          - name: Run tests
            run: npm test    
                